# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    label = "nixos";
    #device = "/dev/disk/by-uuid/a1c5ff64-ef46-4461-9abf-f7e75f949f11";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    label = "boot";
    fsType = "vfat"; 
  };

  swapDevices = [
    { label = "swap"; }
  ];

  nix.maxJobs = lib.mkDefault 8;
}
